# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: output
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - restore_cache:
          name: Save bundle cache
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
          - v1-gems-
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
      - save_cache:
          name: Restore bundle cache
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install cocoapods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - persist_to_workspace:
          root: .
          paths:
            - .
  testlib:
    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: output
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.2.0"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build and run tests
          command: bundle exec fastlane ios testlib        
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
  testui:
    environment:
      BUNDLE_PATH: vendor/bundle
      FL_OUTPUT_DIR: output
    working_directory: /Users/distiller/project
    macos:
      xcode: "10.2.0"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build and run tests
          command: bundle exec fastlane ios testui       
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - testlib:
          requires:
            - build
      - testui:
          requires:
            - build

