# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.96.1"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    cocoapods
    scan(scheme: "wallabag")
  end

  lane :testlib do 
    cocoapods
    scan(scheme: "WallabagTest")
  end

  lane :testui do 
    cocoapods
    scan(scheme: "WallabagTestUi")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cocoapods
    increment_build_number
    gym(scheme: "wallabag")
    pilot(skip_waiting_for_build_processing: true)
#    commit_version_bump(message: 'Build Version Bump by fastlane', force: true)
    
#    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
#    add_git_tag(tag: "build-#{build_number}", force: true)
#    push_to_git_remote
  end

  lane :screenshot do
    cocoapods
    snapshot(scheme: "wallabagScreenshot")
  end

  lane :frame do
    frameit
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    deliver(skip_binary_upload: true, force: true, automatic_release: true)
  end
end
