# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.2"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    cert
    sigh(force: true)
    gym(scheme: "wallabag") # Build your app - more options available
    pilot
  end

  lane :snapshot do
    snapshot(scheme: "wallabagScreenshot")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    deliver(skip_binary_upload: true, force: true, automatic_release: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    
  end
  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
